package jp.glory.practice.agentic.auth.command.infra

import com.github.michaelbull.result.fold
import jp.glory.practice.agentic.auth.command.domain.model.PasswordHash
import jp.glory.practice.agentic.auth.command.domain.service.PasswordHasher
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.stereotype.Component

@Component
class BcryptPasswordHasher(
    private val encoder: BCryptPasswordEncoder,
) : PasswordHasher {
    override fun hash(rawPassword: String): PasswordHash {
        val hashed = encoder.encode(rawPassword) ?: throw IllegalStateException("password hash generation failed")
        return PasswordHash.create(hashed).fold(
            success = { it },
            failure = { throw IllegalStateException("invalid password hash generated by encoder") }
        )
    }
}
